package com.atta.rule.paradise.demo.fact.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person  {

    private Boolean adult;

    private java.math.BigDecimal age;

    private java.util.Set<String> cards;

    private java.util.List<String> fullName;

    private String name;

    public Person() {
    }
    
    public Person(String name, java.math.BigDecimal age, Boolean adult, java.util.List<String> fullName, java.util.Set<String> cards) {
        this.name = name;
        this.age = age;
        this.adult = adult;
        this.fullName = fullName;
        this.cards = cards;
    }

    public Boolean getAdult() {
        return this.adult;
    }
    
    public void setAdult(Boolean adult) {
        this.adult = adult;
    }

    public java.math.BigDecimal getAge() {
        return this.age;
    }
    
    public void setAge(java.math.BigDecimal age) {
        this.age = age;
    }

    public java.util.Set<String> getCards() {
        return this.cards;
    }
    
    public void setCards(java.util.Set<String> cards) {
        this.cards = cards;
    }

    public java.util.List<String> getFullName() {
        return this.fullName;
    }
    
    public void setFullName(java.util.List<String> fullName) {
        this.fullName = fullName;
    }

    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}